-- -----------------------------------------------------
-- MySQL Missing Columns Patch for Namecheap
-- -----------------------------------------------------
ALTER TABLE `tenants`
  ADD COLUMN IF NOT EXISTS `legal_name` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `display_name` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `icao_code` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `iata_code` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `primary_country` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `primary_base` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `support_tier` VARCHAR(255) NOT NULL DEFAULT 'standard',
  ADD COLUMN IF NOT EXISTS `onboarding_status` VARCHAR(255) NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS `expected_headcount` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `headcount_pilots` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `headcount_cabin` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `headcount_engineers` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `headcount_schedulers` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `headcount_training` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `headcount_safety` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `headcount_hr` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `onboarded_at` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `suspended_at` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `roles`
  ADD COLUMN IF NOT EXISTS `role_type` VARCHAR(255) NOT NULL DEFAULT 'tenant';

ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `employment_status` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `fleet_id` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `profile_completion_pct` INT NOT NULL DEFAULT 0;

ALTER TABLE `audit_logs`
  ADD COLUMN IF NOT EXISTS `actor_role` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `result` VARCHAR(255) NOT NULL DEFAULT 'success',
  ADD COLUMN IF NOT EXISTS `reason` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `user_agent` TEXT DEFAULT NULL;

ALTER TABLE `notices`
  ADD COLUMN IF NOT EXISTS `requires_ack` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `target_roles` VARCHAR(255) DEFAULT NULL;

